In [2]:
import pandas as pd
import numpy as np
from faker import Faker
import random

In [3]:
fake = Faker()

print(fake.name())
print(fake.city())

Steven Shepard
Lisastad

In [34]:
num_customers = 10000

customers = []

employment_types = [
    'Salaried',
    'Self-Employed',
    'Bussiness',
    'Freelancer'
]

for customer_id in range(1, num_customers + 1):
    
    customers.append({
        'customer_id': customer_id,
        'first_name' : fake.first_name(),
        'last_name' : fake.last_name(),
        'gender' : random.choice(['Male', 'Female']),
        'date_of_birth' : fake.date_of_birth(minimum_age=21, maximum_age=60),
        'city' : fake.city(),
        'state' : fake.state(),
        'employment_type' : random.choice(employment_types),
        'monthly_income' : random.randint(25000, 200000),
        'signup_date' : fake.date_between(start_date='-3y', end_date='today')

})
    
customers_df = pd.DataFrame(customers)

customers_df.head()

,customer_id,first_name,last_name,gender,date_of_birth,city,state,employment_type,monthly_income,signup_date
0,1,Evan,Chapman,Male,1968-11-27,South Carrieborough,Maine,Self-Employed,33893,2024-05-06
1,2,Carla,Perez,Male,1996-04-12,West Francisco,Missouri,Bussiness,82168,2023-06-14
2,3,Heather,Kim,Female,1993-01-30,Wilkinsonport,Arizona,Freelancer,116070,2023-07-09
3,4,Alicia,Perez,Female,1980-05-20,North Martin,Nebraska,Salaried,175009,2023-06-20
4,5,Connie,Wood,Female,1977-04-16,Jacksonberg,Colorado,Self-Employed,40716,2025-09-29

In [33]:
customers_df.to_csv(
    "../data/raw/customers.csv",
    index=False
)

In [38]:
num_loans = 15000

loan_statuses = [
    "Active",
    "Closed",
    "Default"
]

loans = []

for loan_id in range(1, num_loans + 1):

    customer_id = random.randint(1, num_customers)

    loans.append({
        "loan_id": loan_id,
        "customer_id": customer_id,
        "loan_amount": random.randint(50000, 1000000),
        "interest_rate": round(random.uniform(8, 24), 2),
        "tenure_months": random.choice([6, 12, 24, 36, 48]),
        "loan_status": random.choice(loan_statuses),
        "disbursement_date": fake.date_between(start_date='-2y', end_date='today')
    })

loans_df = pd.DataFrame(loans)

loans_df.head()

,loan_id,customer_id,loan_amount,interest_rate,tenure_months,loan_status,disbursement_date
0,1,6930,487521,21.72,48,Closed,2025-06-30
1,2,1842,983630,11.76,48,Closed,2025-04-05
2,3,1780,831941,19.20,36,Default,2025-09-01
3,4,6840,366026,19.64,36,Closed,2025-11-04
4,5,3810,116700,17.12,48,Active,2026-01-02

In [39]:
print(len(loans_df))

15000

In [40]:
loans_df.to_csv(
    '../data/raw/loans.csv',
    index=False
)

In [9]:
num_transactions = 50000

transaction_types = [
    "UPI",
    "Card",
    "Bank Transfer",
    "Wallet"
]

merchant_categories = [
    "Food",
    "Shopping",
    "Travel",
    "Bills",
    "Entertainment",
    "Healthcare"
]

transactions = []

for transaction_id in range(1, num_transactions + 1):

    transactions.append({
        "transaction_id": transaction_id,
        "customer_id": random.randint(1, num_customers),
        "transaction_date": fake.date_between(start_date='-1y', end_date='today'),
        "transaction_type": random.choice(transaction_types),
        "merchant_category": random.choice(merchant_categories),
        "amount": round(random.uniform(100, 50000), 2)
    })

transactions_df = pd.DataFrame(transactions)

transactions_df.head()

,transaction_id,customer_id,transaction_date,transaction_type,merchant_category,amount
0,1,6264,2025-12-03,Card,Healthcare,18052.15
1,2,9441,2026-02-10,Card,Entertainment,16763.57
2,3,3371,2025-11-10,Bank Transfer,Healthcare,32027.13
3,4,3608,2025-07-27,UPI,Food,8787.62
4,5,8580,2025-09-30,UPI,Bills,48366.90

In [19]:
transactions_df.to_csv(
    '../data/raw/transactions.csv',
    index=False
)

In [15]:
repayments = []

repayment_statuses = [
    "On-Time",
    "Late",
    "Missed"
]

for repayment_id in range(1, 20001):

    repayments.append({
        "repayment_id": repayment_id,
        "loan_id": random.randint(1, num_loans),
        "due_date": fake.date_between(start_date='-1y', end_date='today'),
        "payment_date": fake.date_between(start_date='-1y', end_date='today'),
        "amount_paid": round(random.uniform(1000, 50000), 2),
        "repayment_status": random.choice(repayment_statuses)
    })

repayments_df = pd.DataFrame(repayments)

repayments_df.head()

,repayment_id,loan_id,due_date,payment_date,amount_paid,repayment_status
0,1,5508,2025-09-16,2026-04-20,9521.24,Missed
1,2,9144,2026-04-09,2025-09-22,18498.87,On-Time
2,3,1939,2026-03-12,2025-07-26,24573.49,Missed
3,4,6588,2025-09-02,2026-04-29,8339.99,Late
4,5,10102,2025-07-20,2025-11-26,36234.69,Late

In [20]:
repayments_df.to_csv(
    "../data/raw/repayments.csv",
    index=False
)

In [41]:
print(customers_df.shape)
print(loans_df.shape)
print(transactions_df.shape)
print(repayments_df.shape)

(10000, 10)
(15000, 7)
(50000, 6)
(20000, 6)

In [22]:
customers_df.isnull().sum()

customer_id        0
first_name         0
last_name          0
gender             0
date_of_birth      0
city               0
state              0
employment_type    0
monthly_income     0
signup_date        0
dtype: int64

In [23]:
loans_df.isnull().sum()

loan_id              0
customer_id          0
loan_amount          0
interest_rate        0
tenure_months        0
loan_status          0
disbursement_date    0
dtype: int64

In [24]:
repayments_df.isnull().sum()

repayment_id        0
loan_id             0
due_date            0
payment_date        0
amount_paid         0
repayment_status    0
dtype: int64

In [25]:
transactions_df.isnull().sum()

transaction_id       0
customer_id          0
transaction_date     0
transaction_type     0
merchant_category    0
amount               0
dtype: int64

In [31]:
customers_df['employment_type'].value_counts()

employment_type
Salaried         2575
Bussiness        2488
Freelancer       2476
Self-Employed    2461
Name: count, dtype: int64

# Day 3 — Data Generation

## Objective
Generate realistic fintech datasets using Python.

## Datasets Created
- customers
- loans
- transactions
- repayments

## Tools Used
- Pandas
- Faker
- NumPy