In [2]:
import pandas as pd
import numpy as np

In [3]:
analytics = pd.read_csv(
    '../data/cleaned/customer_loan_analytics.csv'
)

analytics.head()

,customer_id,first_name,last_name,gender,date_of_birth,city,state,employment_type,monthly_income,signup_date,...,disbursement_date,repayment_id,due_date,payment_date,amount_paid,repayment_status,income_segment,high_risk_flag,large_loan_flag,missed_payment_flag
0,1,Larry,Keith,Female,1987-12-15,East Megan,Illinois,Freelancer,62011.0,2024-10-31,...,2024-07-03,17025,2026-03-11,2025-05-16,3758.49,On-Time,Middle income,0,0,0
1,1,Larry,Keith,Female,1987-12-15,East Megan,Illinois,Freelancer,62011.0,2024-10-31,...,2024-07-03,18936,2025-09-04,2025-08-16,9007.61,Late,Middle income,0,0,0
2,1,Larry,Keith,Female,1987-12-15,East Megan,Illinois,Freelancer,62011.0,2024-10-31,...,2026-04-08,13245,2026-04-29,2026-04-12,38096.19,On-Time,Middle income,0,1,0
3,3,Nancy,Peters,Female,1972-04-02,Jessicamouth,Tennessee,Self-Employed,150282.0,2025-04-10,...,2024-10-28,1962,2026-02-15,2025-05-17,46205.70,Late,High income,1,1,0
4,3,Nancy,Peters,Female,1972-04-02,Jessicamouth,Tennessee,Self-Employed,150282.0,2025-04-10,...,2024-10-28,13128,2026-01-26,2025-05-14,2046.68,On-Time,High income,1,1,0

In [11]:
pd.options.display.float_format = '{:,.2f}'.format

CREATE EXECUTIVE KPIs

In [4]:
#KPI 1 — TOTAL LOAN PORTFOLIO
total_loan_portfolio = analytics[
    'loan_amount'
].sum()

total_loan_portfolio

np.float64(10595145398.0)

In [5]:
#KPI 2 — TOTAL CUSTOMERS
total_customers = analytics[
    'customer_id'
].nunique()
total_customers

6663

In [6]:
#KPI 3 — DEFAULT RATE
default_rate = (
    analytics['high_risk_flag']
    .mean()
) * 100

default_rate

np.float64(34.335)

In [7]:
#KPI 4 — MISSED PAYMENT RATE
missed_payment_rate = (
    analytics['missed_payment_flag']
    .mean()
) * 100

missed_payment_rate

np.float64(33.715)

In [9]:
#KPI 5 — AVG LOAN AMOUNT
avg_loan_amount = analytics[
    'loan_amount'
].mean()

avg_loan_amount

np.float64(529757.2699)

In [12]:
#KPI TABLE
dashboard_kpis = pd.DataFrame({

    'metric': [
        'Total Loan Portfolio',
        'Total Customers',
        'Default Rate',
        'Missed Payment Rate',
        'Average Loan Amount'
    ],

    'value': [
        total_loan_portfolio,
        total_customers,
        default_rate,
        missed_payment_rate,
        avg_loan_amount
    ]
})

dashboard_kpis

                 metric             value
0  Total Loan Portfolio 10,595,145,398.00
1       Total Customers          6,663.00
2          Default Rate             34.34
3   Missed Payment Rate             33.72
4   Average Loan Amount        529,757.27

## Executive Dashboard Insight

The dashboard KPIs provide a high-level overview of portfolio health and lending risk exposure.

CREATE DASHBOARD CHART DATASETS

In [13]:
#LOAN STATUS
loan_status_summary = (
    analytics['loan_status']
    .value_counts()
    .reset_index()
)

loan_status_summary.columns = [
    'loan_status',
    'count'
]

loan_status_summary

  loan_status  count
0     Default   6867
1      Closed   6637
2      Active   6496

In [14]:
loan_status_summary.to_csv(
    '../data/cleaned/loan_status_summary.csv',
    index=False
)

In [16]:
#INCOME SEGMENT ANALYSIS
income_segment_summary = (
    analytics.groupby(
        'income_segment'
    )['loan_amount']
    .mean()
    .reset_index()
)

income_segment_summary

  income_segment  loan_amount
0    High income   530,262.91
1     Low income   544,903.91
2  Middle income   521,352.45

## Customer Segmentation Insight

Middle-income and salaried customers appear to dominate the lending portfolio, indicating lower-risk lending behavior.

In [17]:
income_segment_summary.to_csv(
    '../data/cleaned/income_segment_summary.csv',
    index=False
)

In [18]:
#EMPLOYMENT ANALYSIS
employment_summary = (
    analytics.groupby(
        'employment_type'
    )['loan_amount']
    .mean()
    .reset_index()
)

employment_summary

  employment_type  loan_amount
0       Bussiness   532,216.03
1      Freelancer   521,112.27
2        Salaried   531,336.70
3   Self-Employed   534,328.37

In [19]:
employment_summary.to_csv(
    '../data/cleaned/employment_summary.csv',
    index=False
)